const SHEET_CONFIG={id:'1R_IC9N-0nNemXAXpodxzoqkVABEA8s9qL46WLSaO5yM',tabs:{publications:'논문',patents:'특허',people:'인물',news:'뉴스'}};
function parseCSV(text){const rows=[];let row=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++}else quoted=!quoted}else if(c===','&&!quoted){row.push(cell);cell=''}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&text[i+1]==='\n')i++;row.push(cell);cell='';if(row.some(v=>v.trim()))rows.push(row);row=[]}else cell+=c}row.push(cell);if(row.some(v=>v.trim()))rows.push(row);return rows}
function objects(csv){const rows=parseCSV(csv);if(rows.length<2)return[];const h=rows[0].map(x=>x.trim().toLowerCase());return rows.slice(1).map(r=>Object.fromEntries(h.map((x,i)=>[x,(r[i]||'').trim()]))) }
async function getTab(name){const url=`https://docs.google.com/spreadsheets/d/${SHEET_CONFIG.id}/gviz/tq?tqx=out:csv&sheet=${encodeURIComponent(name)}&_=${Date.now()}`;const res=await fetch(url,{cache:'no-store'});if(!res.ok)throw new Error(`HTTP ${res.status}`);return objects(await res.text())}
function placeholder(x){return x.id==='예시'||x['']==='예시'||Object.values(x).some(v=>/SAMPLE_FILE_ID|@example\.com/i.test(String(v||'')))}
function dateValue(v){const d=new Date(String(v||'').replace(/\./g,'-'));return Number.isNaN(d.getTime())?0:d.getTime()}
function chip(label,href){if(!href)return null;const a=document.createElement('a');a.className='chip';a.href=href;a.target='_blank';a.rel='noopener noreferrer';a.textContent=label;return a}
function driveImage(url){const m=String(url||'').match(/\/d\/([^/]+)/);return m?`https://drive.google.com/uc?export=view&id=${m[1]}`:url}
function status(id,msg=''){const el=document.getElementById(id);if(el)el.textContent=msg}
function renderPublications(items){const data=items.filter(x=>x['논문 제목']&&!placeholder(x)&&x['제출 상태']==='Accept').sort((a,b)=>Number(b['연도']||0)-Number(a['연도']||0));const root=document.getElementById('publication-list');root.replaceChildren();data.forEach(x=>{const a=document.createElement('article');a.className='pub';const y=document.createElement('div');y.className='pub-year';y.textContent=x['연도']||'—';const body=document.createElement('div');const title=document.createElement('h3');title.textContent=x['논문 제목'];const authors=document.createElement('p');authors.textContent=x['저자(모두)']||'';const venue=document.createElement('p');venue.className='venue';venue.textContent=x['학회/저널 명']||'';const summary=document.createElement('p');summary.textContent=x['한줄요약(영문)']||'';body.append(title,authors,venue,summary);const links=document.createElement('div');links.className='chips';[chip('GitHub',x['깃허브 주소']),chip('arXiv',x['arxiv주소']),chip('Media',x['이미지/동영상 주소'])].filter(Boolean).forEach(v=>links.append(v));a.append(y,body,links);root.append(a)});status('page-status',`${data.length} accepted publications`) }
function renderPatents(items){const countries={'대한민국':'Republic of Korea','한국':'Republic of Korea','미국':'United States','출원':'Filed','등록':'Registered','공개':'Published'};const data=items.filter(x=>x['특허명']&&!placeholder(x)).sort((a,b)=>dateValue(b['출원일'])-dateValue(a['출원일']));const root=document.getElementById('patent-list');root.replaceChildren();data.forEach(x=>{const a=document.createElement('article');a.className='patent';const top=document.createElement('div');top.className='patent-top';const country=document.createElement('span');country.className='country';country.textContent=countries[x['출원국가']]||x['출원국가']||'—';const badge=document.createElement('span');badge.className='badge';badge.textContent=countries[x['세부상태']]||x['세부상태']||'Filed';top.append(country,badge);const title=document.createElement('h3');title.textContent=x['특허명(영문)']||x['영문 특허명']||x['특허명'];const inventors=document.createElement('p');inventors.textContent=`Inventors · ${x['발명자 (영문)']||x['발명자 (국문)']||'—'}`;const number=document.createElement('p');number.textContent=`Application · ${x['출원번호']||'—'}${x['출원일']?' · '+x['출원일']:''}`;a.append(top,title,inventors,number);const detail=chip('View details →',x['링크']);if(detail)a.append(detail);root.append(a)});status('page-status',`${data.length} patents`) }
function renderPeople(items){const data=items.filter(x=>x['이름']&&!placeholder(x));const root=document.getElementById('people-list');root.replaceChildren();data.forEach(x=>{const a=document.createElement('article');a.className='person';const displayName=x['영문 이름']||x['이름'];const photo=document.createElement('div');photo.className='photo';photo.textContent=(displayName||'R')[0];if(x['사진']){const img=document.createElement('img');img.src=driveImage(x['사진']);img.alt=`${displayName}, researcher`;img.loading='lazy';img.onerror=()=>img.remove();photo.append(img)}const body=document.createElement('div');body.className='person-body';const name=document.createElement('h3');name.textContent=displayName;const en=document.createElement('div');en.className='english';en.textContent='';const role=document.createElement('div');role.className='role';role.textContent=x['역할']||'Researcher';const field=document.createElement('div');field.className='field';field.textContent=x['연구 분야']||'';const links=document.createElement('div');links.className='chips';[chip('Email',x['이메일']?`mailto:${x['이메일']}`:''),chip('Homepage',x['개인 홈페이지']),chip('Scholar',x['google scholar'])].filter(Boolean).forEach(v=>links.append(v));body.append(name,en,role,field,links);a.append(photo,body);root.append(a)});status('page-status',`${data.length} researchers`) }
function renderNews(items){const data=items.filter(x=>x['뉴스 제목']).sort((a,b)=>dateValue(b['날짜'])-dateValue(a['날짜'])).slice(0,5);if(!data.length)return;const first=data[0],box=document.getElementById('featured-news');box.querySelector('time').textContent=first['날짜'];box.querySelector('h3').textContent=first['뉴스 제목'];box.querySelector('p').textContent=first['뉴스 내용']||'';if(first['링크']){box.style.cursor='pointer';box.onclick=()=>window.open(first['링크'],'_blank','noopener')}const root=document.getElementById('news-list');root.replaceChildren();data.slice(1).forEach(x=>{const a=document.createElement(x['링크']?'a':'div');a.className='news-item';if(x['링크']){a.href=x['링크'];a.target='_blank';a.rel='noopener noreferrer'}const time=document.createElement('time');time.textContent=x['날짜'];const b=document.createElement('b');b.textContent=x['뉴스 제목'];a.append(time,b);root.append(a)})}
async function loadPage(kind){try{const rows=await getTab(SHEET_CONFIG.tabs[kind]);({publications:renderPublications,patents:renderPatents,people:renderPeople,news:renderNews})[kind](rows)}catch(e){console.error(e);status(kind==='news'?'news-status':'page-status','Unable to load data. Check the Google Sheets sharing and web publishing settings.')}}
document.addEventListener('DOMContentLoaded',()=>{const kind=document.body.dataset.page;if(kind&&kind!=='home')loadPage(kind);if(document.getElementById('featured-news'))loadPage('news');document.querySelector('.hamb')?.addEventListener('click',()=>document.querySelector('.menu')?.classList.toggle('open'))});
